.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. shiabit_qt test_shiabit_qt
clean: FORCE
	$(MAKE) -C .. shiabit_qt_clean test_shiabit_qt_clean
check: FORCE
	$(MAKE) -C .. test_shiabit_qt_check
shiabit-qt shiabit-qt.exe: FORCE
	 $(MAKE) -C .. shiabit_qt
