.TH SHIABIT-CLI "1" "February 2016" "shiabit-cli 0.12"
.SH NAME
shiabit-cli \- a remote procedure call client for Shiabit Core. 
.SH SYNOPSIS
shiabit-cli [options] <command> [params] \- Send command to Shiabit Core. 
.TP
shiabit-cli [options] help \- Asks Shiabit Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the shiabit-cli program. shiabit-cli is an RPC client used to send commands to Shiabit Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBshiabitd\fP, \fBshiabit.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
